name: Sync with Upstream

# Controls when the workflow will run
on:
#   schedule:
#     - cron: '*/5 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.SYNC_GH_ACTIONS_PAT }} 
      # The repos provided need to be in the {owner}/{repo} format
      FORK_REPO: yusuf-musleh/tester-repo  # TODO: do not hardcode
      UPSTREAM_REPO: tester-org-1/tester-repo  # TODO: do not hardcode
      FORK_RELEASE: "main"
      UPSTREAM_MASTER: "master"

    steps:
      - name: Get and store current datetime stamp
        id: current-datetime-stamp
        run: echo "DATE_TIME_STAMP=$(date +'%Y%m%d-%s')" >> "$GITHUB_OUTPUT"
      - name: Configure git to use GitHub Cli for credentials
        run: gh auth setup-git -h github.com
      - name: Checkout Forked Repo
        uses: actions/checkout@v3
        with:
          repository: ${{ env.FORK_REPO }}
          token: ${{ secrets.SYNC_GH_ACTIONS_PAT }}
      - name: Add Remote Upstream
        run: git remote add upstream $UPSTREAM_REPO
      - name: Fetch Latest from Upstream
        run: git fetch upstream
      - name: Create a new branch off Upstream master
        run: git checkout -b sync--${{ steps.current-datetime-stamp.outputs.DATE_TIME_STAMP }} upstream/$UPSTREAM_MASTER
      - name: Push new branch to Fork
        run: git push origin
      - name: Create PR on Fork with latest changes from Upstream
        run: >
          gh pr create
          --repo $FORK_REPO
          --base $FORK_RELEASE
          --head $(git branch --show-current)
          --title "Sync Upstream ${{ steps.current-datetime-stamp.outputs.DATE_TIME_STAMP }}"
          --body "Syncing with Upstream"
