name: Sync with Upstream

# Controls when the workflow will run
on:
#   schedule:
#     - cron: '*/5 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.SYNC_GH_ACTIONS_PAT }}
      FORK_REPO: git@github.com:yusuf-musleh/tester-repo.git  # TODO: do not hardcode
      FORK_RELEASE: "main"

    steps:
#       - name: Set GitHub CLI to use SSH for git
#         run: gh config set git_protocol ssh --host github.com
      - name: Authenticate GitHub Cli
        run: gh auth setup-git -h github.com
      - name: GitHub Cli Auth Status
        run: gh auth status
      - name: Clone Forked Repo
        # This automatically detects its a fork and adds a remote for upstream called `upstream`
        run: gh repo clone $FORK_REPO
      - name: Fetch Latest from Upstream
        run: git fetch upstream
      - name: Create a new branch off Upstream master
        run: git checkout -b sync--$(date +"%Y-%m-%d")
      - name: Push new branch to Fork
        run: git push origin
      - name: Create PR on Fork with latest changes from Upstream
        run: >
          gh pr create
          --repo $FORK_REPO
          --base $FORK_RELEASE
          --head $(git branch --show-current)
          --title "Sync Upstream $(date +'%Y-%m-%d')"
          --body "Syncing with Upstream"
